GET http://localhost:3000

###
POST http://localhost:3000/assets
Content-Type: application/json

{
  "id": "asset1",
  "symbol": "A1",
  "price": 100
}

###
GET http://localhost:3000/assets

###
GET http://localhost:3000/wallets

###
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "id": "wallet1"
}

###
GET http://localhost:3000/wallet1/assets