GET http://localhost:3000

###
POST http://localhost:3000/assets
Content-Type: application/json

{
  "id": "asset2",
  "symbol": "A2",
  "price": 100
}

###
GET http://localhost:3000/assets

###
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "id": "wallet1"
}
###
POST http://localhost:3000/wallets
Content-Type: application/json

{
  "id": "wallet2"
}

###
GET http://localhost:3000/wallets


###
GET http://localhost:3000/wallets/wallet1/assets
# Content-Type: application/json
# {
#   "id": "wallet1"
# }

###
POST http://localhost:3000/wallets/wallet1/assets
Content-Type: application/json

{
  "asset_id": "asset1",
  "shares": 10
}

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "wallet_id": "wallet1",
  "asset_id": "asset2",
  "shares": 5,
  "price": 100,
  "type": "BUY"
}