import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-gray-50 h-screen flex flex-col">
        {children}
        {/* <DefaultNavbr />
        <FlowbiteContext>
        </FlowbiteContext> */}
        </body>
    </html>
  )
}
